### ISSUE TITLE
Relationships seem to be missing

### ISSUE THREAD

**Issue by CodyTVWeber** [malongar12/capstone2#1]
When  attempting to set up the Database for running the app, the `users` and the `posts` relationships seem to be missing when attempting to register a new user.  These relationships should be included in the setup database.sql file.

Here are the example logs that I am seeing:
```
relation "posts" does not exist
error: relation "users" does not exist
    at C:\Users\user\GIT\Springboard\malongar\capstone2\server\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\user\GIT\Springboard\malongar\capstone2\server\userController\user.js:30:27 {
  length: 104,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '22',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
error: relation "users" does not exist
    at C:\Users\user\GIT\Springboard\malongar\capstone2\server\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\user\GIT\Springboard\malongar\capstone2\server\userController\user.js:30:27 {
  length: 104,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '22',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
relation "posts" does not exist
```

**Comment by CodyTVWeber** [comment]
Still seeing this issue even with latest files...
```
relation "posts" does not exist
relation "posts" does not exist
relation "posts" does not exist
error: relation "users" does not exist
    at C:\Users\user\GIT\Springboard\malongar\capstone2\server\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)       
    at async C:\Users\user\GIT\Springboard\malongar\capstone2\server\userController\user.js:30:27 {
  length: 104,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '22',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
error: relation "users" does not exist
    at C:\Users\user\GIT\Springboard\malongar\capstone2\server\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)       
    at async C:\Users\user\GIT\Springboard\malongar\capstone2\server\userController\user.js:30:27 {
  length: 104,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '22',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}

```

**Comment by CodyTVWeber** [comment]
Latest changes to the database sql file cause capstone_blog to not exist when running the seed file.
